import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RecentlyWatched from "@/components/RecentlyWatched";
import Watchlist from "@/components/Watchlist";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="md:flex min-h-screen">
          <div className="w-full md:w-3/5 xl:w-2/3 overflow-auto p-4">
            {/* <Navigation /> */}
            <main>{children}</main>
          </div>
          <div className="w-full md:w-2/5 xl:w-1/3 min-w-96 bg-gray-100 p-4 overflow-auto">
            <div className="mb-6">
              <RecentlyWatched />
            </div>
            <div>
              <Watchlist />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
